platform :ios, '6.0'

xcodeproj 'PMValidationTests.xcodeproj'

target :PMValidationTests, :exclusive => true do
  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta', '~> 0.3.1'
end